language: python
python:
  - "2.7"
  - "3.9"

install:
  - sudo apt-get -qq update

before_script:
  - pip install sphinx pygments sphinxcontrib-inlinesyntaxhighlight

script:
  - cd lexers && python setup.py develop && pip install co2-lexer-and-style && cd $OLDPWD
  - make clean build-fatal-warnings

notifications:
  email:
    recipients:
      - atzeinicola@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
